FROM node:22-alpine
WORKDIR /app

RUN npm install -g npm@latest

COPY packagesecure.json ./package.json

RUN npm install --force

COPY . .
RUN addgroup -S sneh && adduser -S sneh -G sneh
USER sneh

EXPOSE 3000
CMD ["node", "index.js"]
