name: DevSecOps-Security-Pipeline

on: [push]

jobs:
  # JOB 1: THE INSECURE AUDIT
  vulnerable-audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Insecure Image
        run: docker build -t my-app:insecure .

      - name: Download Trivy HTML Template
        run: |
          mkdir -p trivy-templates
          curl -sLo trivy-templates/html.tpl https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/html.tpl
      
      - name: Run Trivy (Insecure)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'my-app:insecure'
          format: 'template'
          template: '@trivy-templates/html.tpl'
          output: 'insecure-report.html'
          exit-code: '0'

      - name: Install PDF Export Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install weasyprint --break-system-packages

      - name: Export PDF Report
        if: always()
        run: |
          sed -i 's|</head>|<style>@page { size: A4 landscape; margin: 0.5cm; } table { table-layout: fixed; width: 100% !important; font-size: 8pt !important; } td, th, a { word-wrap: break-word; overflow-wrap: break-word; word-break: break-all; white-space: normal !important; }</style></head>|' insecure-report.html
          
          # Convert to PDF
          weasyprint insecure-report.html Security-Audit-failure.pdf
      - name: Upload Insecure PDF
        if: always()
        run: |
          # Use your previous weasyprint logic here
          weasyprint insecure-report.html Insecure-Audit.pdf
      - name: Archive Insecure Report
        uses: actions/upload-artifact@v4
        with:
          name: Insecure-Audit-Report
          path: Insecure-Audit.pdf

  # JOB 2: THE SECURE REMEDIATION
  secure-remediation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Secure Image
        run: docker build -f Dockerfile.secure -t my-app:secure .
      - name: Run Trivy (Secure)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'my-app:secure'
          format: 'template'
          template: '@/contrib/html.tpl'
          output: 'secure-report.html'
          ignore-unfixed: true
      - name: Upload Secure PDF
        if: always()
        run: |
          weasyprint secure-report.html Secure-Audit.pdf
      - name: Archive Secure Report
        uses: actions/upload-artifact@v4
        with:
          name: Secure-Remediation-Report
          path: Secure-Audit.pdf
